<?php
require_once __DIR__.'/core/bootstrap.php';$user=require_login($pdo);require_once __DIR__.'/repositories/UserRepository.php';require_once __DIR__.'/services/CodeDnaService.php';$repo=new UserRepository($pdo);$all=$repo->all(false);$a=(string)($_GET['a']??$user['id']);$b=(string)($_GET['b']??'');if($b===''){foreach($all as $x){if($x['id']!==$a){$b=$x['id'];break;}}}$ua=$repo->find($a);$ub=$repo->find($b);$dnaSvc=new CodeDnaService($pdo);$da=$ua?$dnaSvc->calculate($a):null;$db=$ub?$dnaSvc->calculate($b):null;
$pageTitle='Rivalry';include __DIR__.'/includes/header.php';?>
<div class="page-head"><div><div class="eyebrow">Head-to-Head Analytics</div><h1>Rivalry Lab</h1><p>Compare two programmers using live database statistics and their calculated Code DNA profiles.</p></div></div>
<form class="card filter-bar" method="get"><select class="form-select" name="a"><?php foreach($all as $x):?><option value="<?=e($x['id'])?>" <?=$x['id']===$a?'selected':''?>><?=e($x['username'])?></option><?php endforeach;?></select><span class="versus">VS</span><select class="form-select" name="b"><?php foreach($all as $x):?><option value="<?=e($x['id'])?>" <?=$x['id']===$b?'selected':''?>><?=e($x['username'])?></option><?php endforeach;?></select><button class="btn btn-primary">Compare</button></form>
<?php if($ua&&$ub&&$da&&$db):?><div class="card card-pad race-card"><div class="center"><div class="avatar" style="margin:auto"><?=e(strtoupper(substr($ua['username'],0,1)))?></div><h2><?=e($ua['username'])?></h2><div class="text-cyan" style="font-size:26px;font-weight:800"><?=(int)$ua['rating']?></div><small class="muted"><?=e($ua['rank'])?> · <?=e($ua['university'])?></small></div><div class="versus">VS</div><div class="center"><div class="avatar" style="margin:auto"><?=e(strtoupper(substr($ub['username'],0,1)))?></div><h2><?=e($ub['username'])?></h2><div class="text-cyan" style="font-size:26px;font-weight:800"><?=(int)$ub['rating']?></div><small class="muted"><?=e($ub['rank'])?> · <?=e($ub['university'])?></small></div></div>
<div class="grid grid-2" style="margin-top:18px"><div class="card card-pad"><h3><?=e($ua['username'])?> · Code DNA</h3><?php foreach($da['dimensions'] as $k=>$v):?><div class="metric-row"><label><?=e($da['dimension_labels'][$k])?></label><div class="progress"><span style="width:<?=$v?>%"></span></div><b><?=$v?>%</b></div><?php endforeach;?></div><div class="card card-pad"><h3><?=e($ub['username'])?> · Code DNA</h3><?php foreach($db['dimensions'] as $k=>$v):?><div class="metric-row"><label><?=e($db['dimension_labels'][$k])?></label><div class="progress"><span style="width:<?=$v?>%"></span></div><b><?=$v?>%</b></div><?php endforeach;?></div></div>
<div class="grid grid-4" style="margin-top:18px"><div class="card stat"><div class="label">Solved</div><div class="value"><?=$ua['solved_count']?> : <?=$ub['solved_count']?></div></div><div class="card stat"><div class="label">Submissions</div><div class="value"><?=$ua['submission_count']?> : <?=$ub['submission_count']?></div></div><div class="card stat"><div class="label">DNA overall</div><div class="value cyan"><?=$da['overall']?> : <?=$db['overall']?></div></div><div class="card stat"><div class="label">Rating gap</div><div class="value amber"><?=abs((int)$ua['rating']-(int)$ub['rating'])?></div></div></div><?php endif;?>
<?php include __DIR__.'/includes/footer.php';?>
