<?php
require_once __DIR__ . '/core/bootstrap.php';require_once __DIR__ . '/services/SqlBattleService.php';
$user=require_login($pdo);$service=new SqlBattleService($pdo);$id=trim((string)($_GET['id']??''));$battle=$service->battle($id);if(!$battle){http_response_code(404);exit('Battle not found.');}if(!in_array($user['id'],[$battle['player1_id'],$battle['player2_id']],true)&&$user['role']!=='admin'){http_response_code(403);exit('Not a battle participant.');}
$result=null;$error=null;$query=(string)($_POST['query']??'');if(request_method('POST')){verify_csrf();try{$result=$service->submit((string)$battle['challenge_id'],(string)$user['id'],$query,$id);$battle=$service->battle($id);}catch(Throwable $e){$error=user_safe_error($e,'Could not process the SQL battle request.');}}
$attempts=$service->attemptsForBattle($id);$best=[];foreach($attempts as $a){$uid=(string)$a['user_id'];$best[$uid]=max($best[$uid]??0,(int)$a['score']);}$pageTitle='SQL Battle · '.$battle['title'];include __DIR__.'/includes/header.php';
?>
<div class="page page-sm"><section class="race-stage card mb-3"><div class="race-player"><span class="eyebrow">Player 1</span><h2><?= e($battle['player1_name']) ?></h2><div class="dna-score"><?= (int)($best[$battle['player1_id']]??0) ?><small> pts</small></div></div><div class="race-vs"><div class="vs">SQL Battle</div><div class="timer">VS</div><span class="pill <?= $battle['status']==='completed'?'pill-easy':'pill-medium' ?>"><?= e(strtoupper($battle['status'])) ?></span></div><div class="race-player"><span class="eyebrow">Player 2</span><h2><?= e($battle['player2_name']) ?></h2><div class="dna-score"><?= (int)($best[$battle['player2_id']]??0) ?><small> pts</small></div></div></section>
<?php if($battle['status']==='completed'): ?><div class="alert alert-success"><strong>Battle complete.</strong> <?= $battle['winner_name']?e($battle['winner_name']).' wins with the higher accepted score.':'The battle ended in a score tie.' ?></div><?php endif; ?><?php if($error): ?><div class="alert alert-error"><?= e($error) ?></div><?php endif; ?>
<section class="grid grid-2"><div class="card card-pad"><span class="eyebrow"><?= e($battle['difficulty']) ?> challenge</span><h2><?= e($battle['title']) ?></h2><p class="muted"><?= e($battle['description']) ?></p><div class="code-box">Allowed: SELECT / WITH
Tables: arena_users, arena_universities, arena_problems, arena_submissions
Scoring: 700 correctness + 150 speed + 150 efficiency</div><?php if($battle['status']==='active' && in_array($user['id'],[$battle['player1_id'],$battle['player2_id']],true)): ?><form method="post" class="form-grid mt-2"><?= csrf_field() ?><div class="field full"><label>Your SQL</label><textarea class="textarea sql-editor" data-tab-indent name="query" required><?= e($query) ?></textarea></div><div class="field full"><button class="btn btn-primary">Submit battle query</button></div></form><?php endif; ?><?php if($result): ?><div class="alert <?= $result['correct']?'alert-success':'alert-info' ?> mt-2"><strong><?= e(strtoupper(str_replace('_',' ',$result['status']))) ?></strong> · <?= (int)$result['score'] ?> points · <?= e($result['feedback']) ?></div><?php endif; ?></div><div class="card"><div class="card-head"><h3>Attempt feed</h3><span class="pill pill-neutral"><?= count($attempts) ?></span></div><div class="list" style="padding:0 18px"><?php foreach(array_reverse($attempts) as $a): ?><div class="list-item"><div><strong><?= e($a['username']) ?></strong><div class="muted small"><?= e(date('H:i:s',strtotime($a['submitted_at']))) ?> · efficiency <?= (int)$a['efficiency_score'] ?>%</div></div><div class="text-right"><strong class="<?= $a['status']==='accepted'?'status-success':'status-warning' ?>"><?= e(strtoupper(str_replace('_',' ',$a['status']))) ?></strong><div class="small"><?= (int)$a['score'] ?> pts</div></div></div><?php endforeach; ?><?php if(!$attempts): ?><div class="empty">Waiting for the first query.</div><?php endif; ?></div></div></section></div>
<?php include __DIR__.'/includes/footer.php'; ?>
