<?php
require_once __DIR__ . '/core/bootstrap.php';require_once __DIR__ . '/services/GhostRaceService.php';
$user=require_login($pdo);$service=new GhostRaceService($pdo);$error=null;
if(request_method('POST')){verify_csrf();try{$raceId=$service->createRace((string)$user['id'],(string)($_POST['ghost_session']??''),(int)($_POST['speed']??4));redirect('ghost_race_play.php?id='.urlencode($raceId));}catch(Throwable $e){$error=$e->getMessage();}}
$ghosts=$service->availableGhosts((string)$user['id']);$history=$service->history((string)$user['id']);$pageTitle='Ghost Race';include __DIR__.'/includes/header.php';
?>
<main class="page"><div class="page-head"><div><span class="eyebrow">Feature · historical competition</span><h1 class="page-title">👻 Ghost Race</h1><p class="page-subtitle">Race against the recorded solving journey of another user. No live opponent or WebSocket is required—the database replays their historical submission events at the original elapsed times.</p></div></div><?php if($error): ?><div class="alert alert-error"><?= e($error) ?></div><?php endif; ?>
<section class="grid grid-3 mb-3"><div class="card card-pad span-2"><span class="eyebrow">Start a race</span><h2>Choose a historical run</h2><form method="post" class="form-grid"><?= csrf_field() ?><div class="field full"><label>Ghost run</label><select class="select" name="ghost_session" required><?php foreach($ghosts as $g): ?><option value="<?= e($g['session_id']) ?>"><?= e($g['problem_title']) ?> · <?= e($g['ghost_username']) ?> · <?= e(format_duration((int)$g['solve_time_seconds'])) ?> · <?= (int)$g['attempts'] ?> attempts</option><?php endforeach; ?></select></div><div class="field"><label>Playback speed</label><select class="select" name="speed"><option value="1">1× real time</option><option value="2">2×</option><option value="4" selected>4× demo speed</option></select></div><div class="field" style="justify-content:end"><button class="btn btn-primary" <?= !$ghosts?'disabled':'' ?>>Launch Ghost Race</button></div></form><?php if(!$ghosts): ?><div class="alert alert-info mt-2">No opponent history exists yet. Create solved sessions from the Practice Arena first.</div><?php endif; ?></div><div class="card card-pad"><span class="eyebrow">How it works</span><h3>Replay, don’t reveal</h3><p class="muted small">CodeForge never exposes the ghost’s source code. It replays only timestamps and verdicts: START → WA/TLE → AC. Your goal is to reach AC before their historical finish time.</p><div class="stat-row"><span>Historical event replay</span><span class="status-success">✓</span></div><div class="stat-row"><span>Real-time timer</span><span class="status-success">✓</span></div><div class="stat-row"><span>Post-race analytics</span><span class="status-success">✓</span></div></div></section>
<section class="card"><div class="card-head"><h3>Your race history</h3><span class="pill pill-neutral"><?= count($history) ?> recent</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Problem</th><th>Ghost</th><th>Result</th><th>You</th><th>Ghost time</th><th>Speed</th><th>When</th></tr></thead><tbody><?php foreach($history as $r): ?><tr><td class="strong"><?= e($r['problem_title']) ?></td><td><?= e($r['ghost_username']) ?></td><td class="strong <?= $r['result']==='won'?'status-success':($r['result']==='active'?'status-info':'status-danger') ?>"><?= e(strtoupper($r['result'])) ?></td><td><?= $r['challenger_time']!==null?e(format_duration((int)$r['challenger_time'])):'—' ?></td><td><?= e(format_duration((int)$r['ghost_time'])) ?></td><td><?= (int)$r['playback_speed'] ?>×</td><td><?= e(date('M d, H:i',strtotime($r['started_at']))) ?></td></tr><?php endforeach; ?><?php if(!$history): ?><tr><td colspan="7" class="empty">No races yet.</td></tr><?php endif; ?></tbody></table></div></section>
</main><?php include __DIR__.'/includes/footer.php'; ?>
