<?php
require_once __DIR__.'/core/bootstrap.php';$user=require_login($pdo);
require_once __DIR__.'/services/ProblemPracticeService.php';$service=new ProblemPracticeService($pdo);
$problemId=trim((string)($_GET['id']??$_POST['problem_id']??''));
$stmt=$pdo->prepare('SELECT * FROM problems WHERE id=:id');$stmt->execute(['id'=>$problemId]);$problem=$stmt->fetch();if(!$problem){http_response_code(404);exit('Problem not found');}
$sessionId=trim((string)($_GET['session']??$_POST['session_id']??''));
if($sessionId===''){$sessionId=$service->getOrCreateSession($user['id'],$problemId)['id'];redirect('solve.php?id='.urlencode($problemId).'&session='.urlencode($sessionId));}
$result=null;if(request_method('POST')){verify_csrf();try{$result=$service->submit($user['id'],$sessionId,$problemId,(string)($_POST['source_code']??''),(string)($_POST['language']??'C++'));}catch(Throwable $e){flash('error',$e->getMessage());redirect('solve.php?id='.urlencode($problemId).'&session='.urlencode($sessionId));}}
$attempts=$service->sessionAttempts($sessionId);$pageTitle=$problem['title'];include __DIR__.'/includes/header.php';
?>
<div class="page-head"><div><div class="eyebrow"><?=e($problem['topic'])?> · <?=e($problem['difficulty'])?></div><h1><?=e($problem['title'])?></h1><p><?=e($problem['description'])?></p></div><a class="btn btn-secondary" href="problems.php"><i class="bi bi-arrow-left"></i>Library</a></div>
<div class="grid grid-2"><div class="card card-pad"><div class="card-head"><h3>Problem brief</h3><span class="pill <?=difficulty_class($problem['difficulty'])?>"><?=e($problem['difficulty'])?></span></div><p class="muted" style="line-height:1.75"><?=e($problem['description'])?></p><div class="callout"><strong>Prototype judge:</strong> this pre-framework version uses a deterministic simulation judge so the DBMS and feature flows are testable without executing untrusted code. A sandboxed real judge can replace it during framework migration.</div><h3 class="section-title">Session attempts</h3><div class="list"><?php foreach($attempts as $a):?><div class="list-item"><div><strong class="<?=verdict_class($a['verdict'])?>"><?=e($a['verdict'])?></strong><br><small><?=format_duration((int)$a['elapsed_seconds'])?> · <?=e($a['language'])?></small></div><span class="mono muted"><?=(int)$a['runtime_ms']?> ms</span></div><?php endforeach;?><?php if(!$attempts):?><span class="muted">No submissions yet.</span><?php endif;?></div></div>
<div class="card card-pad"><div class="card-head"><h3>Code workspace</h3><span class="badge-dot text-green">Session active</span></div><?php if($result):?><div class="toast-banner <?=$result['verdict']==='AC'?'success':'danger'?>"><strong><?=e($result['verdict'])?></strong> · <?=e($result['feedback'])?></div><?php endif;?><form method="post"><?=csrf_field()?><input type="hidden" name="problem_id" value="<?=e($problemId)?>"><input type="hidden" name="session_id" value="<?=e($sessionId)?>"><label class="form-label">Language</label><select class="form-select" name="language" style="margin-bottom:12px"><option>C++</option><option>Python</option><option>Java</option></select><textarea class="code-editor" name="source_code" spellcheck="false"><?=e($problem['starter_code']??'')?></textarea><div class="hero-actions"><button class="btn btn-primary"><i class="bi bi-send"></i>Submit solution</button><a class="btn btn-secondary" href="solve.php?id=<?=e($problemId)?>"><i class="bi bi-arrow-repeat"></i>New session</a></div></form></div></div>
<?php include __DIR__.'/includes/footer.php';?>
