<?php
require_once __DIR__ . '/core/bootstrap.php';$admin=require_admin($pdo);$query=trim((string)($_POST['query']??''));$rows=[];$error=null;$columns=[];
function validate_admin_read_query(string $query):array{$q=trim(preg_replace('/;\s*$/','',$query)??$query);if($q==='')return[false,'Enter a query.'];if(str_contains($q,';'))return[false,'One statement at a time.'];if(!preg_match('/^(SELECT|SHOW|DESCRIBE|DESC|EXPLAIN)\b/i',$q))return[false,'SQL Lab is read-only: SELECT, SHOW, DESCRIBE and EXPLAIN only.'];if(preg_match('/\b(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|TRUNCATE|REPLACE|GRANT|REVOKE|OUTFILE|DUMPFILE|LOAD_FILE|SLEEP|BENCHMARK)\b/i',$q))return[false,'Mutating or dangerous SQL is blocked.'];return[true,$q];}
if(request_method('POST')){verify_csrf();[$ok,$value]=validate_admin_read_query($query);if(!$ok){$error=$value;}else{try{$start=microtime(true);$stmt=$pdo->query($value);$rows=$stmt->fetchAll();$elapsed=round((microtime(true)-$start)*1000,3);$columns=$rows?array_keys($rows[0]):[];}catch(PDOException $e){$error=$e->getMessage();}}}
$pageTitle='SQL Lab';include __DIR__.'/includes/header.php';
?>
<main class="page"><div class="page-head"><div><span class="eyebrow">Administrator · DBMS demonstration</span><h1 class="page-title">SQL Lab</h1><p class="page-subtitle">The old broken MySQLi console has been replaced with a PDO-based read-only explorer. It is suitable for live JOIN, GROUP BY, subquery and EXPLAIN demonstrations without allowing destructive statements.</p></div></div><?php if($error): ?><div class="alert alert-error"><?= e($error) ?></div><?php endif; ?><section class="grid grid-3"><div class="card card-pad"><span class="eyebrow">Examples</span><h3>Try a query</h3><div class="code-box">SELECT p.topic, COUNT(*) problems
FROM problems p
GROUP BY p.topic
ORDER BY problems DESC;</div><div class="code-box mt-2">EXPLAIN SELECT *
FROM submissions
WHERE user_id = 'u1'
AND verdict = 'AC';</div></div><div class="card card-pad span-2"><form method="post" class="form-grid"><?= csrf_field() ?><div class="field full"><label>Read-only SQL</label><textarea class="textarea sql-editor" data-tab-indent name="query" placeholder="SELECT ..."><?= e($query) ?></textarea></div><div class="field full"><button class="btn btn-primary">Execute query</button></div></form><?php if(isset($elapsed)): ?><div class="alert alert-success mt-2">Query completed in <?= e($elapsed) ?> ms · <?= count($rows) ?> rows returned.</div><?php endif; ?><?php if($columns): ?><div class="table-wrap"><table class="table"><thead><tr><?php foreach($columns as $c): ?><th><?= e($c) ?></th><?php endforeach; ?></tr></thead><tbody><?php foreach(array_slice($rows,0,200) as $row): ?><tr><?php foreach($row as $v): ?><td><?= e($v) ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></section></main>
<?php include __DIR__.'/includes/footer.php'; ?>
